[package]
name = "fargo-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
pretty_env_logger = "0.4"
rpassword = "5"
rand = "0.8"
structopt = "0.3"
anyhow = "1"
log = "0.4"
fargo = { path = ".." }
